server:
  port: 8081

spring:
  application:
    name: customer-transaction
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:dbbanca;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      platform: h2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8085/eureka/